name: Update Docs

on:
  workflow_dispatch:
  push:
    branches: [1.21.x]
    paths:
      - "Obsidian.API/**/*.cs"
      - "Obsidian.API/*.csproj"
      - "Obsidian/Assets/**/*.json"
      - "Obsidian.SourceGenerators/**/*.cs"
      - "Obsidian.SourceGenerators/*.csproj"
      - ".github/workflows/dockfx.yml"
jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="ObsidianMC" 
          repo_name="Documentation"  
          event_type="trigger-workflow" 

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\",\"client_payload\":{\"unit\":false,\"integration\":true}}"
