name: .NET Build

on:
  workflow_dispatch:
  push:
    branches: [ 1.* ]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - ".github/workflows/dotnet.yml"
  pull_request:
    branches: [ 1.* ]
    paths:
      - "**/*.cs"
      - "**/*.csproj"
      - ".github/workflows/dotnet.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: xXx_set_env_variables_xXx
      run: echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:DebugType=None /p:WarningLevel=0 -v diag
    - name: Rename executables
      working-directory: /home/runner/work/Obsidian/Obsidian/Obsidian.ConsoleApp/bin/Release/net9.0/
      run: |
        mv Obsidian.ConsoleApp.dll ObsidianApp.dll
        mv Obsidian.ConsoleApp.deps.json ObsidianApp.deps.json
        mv Obsidian.ConsoleApp.runtimeconfig.json ObsidianApp.runtimeconfig.json
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Obsidian-Nightly-Build
        path: /home/runner/work/Obsidian/Obsidian/Obsidian.ConsoleApp/bin/Release/net9.0/
      if: ${{ github.event_name == 'push' }} # Only upload artifacts on push, don't upload them for PRs
    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v4.0.0
      with:
        webhook-url: ${{ secrets.BUILD_WEBHOOK }}
        embed-title: New Obsidian build available!
        embed-description: |
          Developer: [`${{ github.actor }}`](https://github.com/${{ github.actor }})
          GH Actions Run: [`${{ github.run_id }}`](https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}) _(Download under "artifacts")_
          Commit SHA: [`${{ github.sha }}`](https://github.com/${{github.repository}}/commit/${{github.sha}})
        embed-color: 2424876
        embed-footer-text: "Obsidian, A C# implementation of the Minecraft server protocol."
      if: ${{ github.event_name == 'push' }} # Only publish webhook on push.
